# Generated by Django 3.2.10 on 2022-01-03 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('CN', 'China'), ('DK', 'Denmark'), ('UK', 'England'), ('FR', 'France'), ('DE', 'Germany'), ('HK', 'Hong Kong'), ('IN', 'India'), ('ID', 'Indonesia'), ('JP', 'Japan'), ('KR', 'Korea'), ('MY', 'Malaysia'), ('RU', 'Russia'), ('SG', 'Singapore'), ('ES', 'Spain'), ('TW', 'Taiwan'), ('TH', 'Thailand'), ('VN', 'Vietnam')], max_length=2, verbose_name='Country')),
                ('handedness', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1, verbose_name='Handedness')),
                ('height', models.PositiveIntegerField(verbose_name='Height (cm)')),
                ('professional', models.BooleanField(default=False, verbose_name='Professional')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
