# Generated by Django 3.2.10 on 2022-01-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rally_number', models.PositiveIntegerField(verbose_name='Rally Number')),
                ('sequence', models.TextField(verbose_name='Sequence')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rallies', to='matches.game', verbose_name='Game')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player', verbose_name='Loser')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player', verbose_name='Service')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Rally',
                'verbose_name_plural': 'Rallies',
            },
        ),
    ]
